### PR TITLE
Created list of supported Point Cloud formats

### LINKED ISSUE #500: [BUG] OBJ file format causes the OIP to crash
**Describe the bug**
Upon opening .obj file in OIP, OIP crashes.  

**To Reproduce**
1. In CMAKE select OIP_WITH_POINT_CLOUD_PROCESSING and generate solution anew
2. Build OpenInfraPlatform.PointCloudProcessing
3. Start OIP
4. Open .obj file
5. See error

**Expected behavior**
OIP should not crash upon opening .obj files

### LINKED ISSUE #503: [BUG] PTX file format causes the OIP to crash
**Describe the bug**
Upon opening .ptx file in OIP, OIP crashes.

**To Reproduce**

1. In CMAKE select OIP_WITH_POINT_CLOUD_PROCESSING and generate solution anew
2. Build OpenInfraPlatform.PointCloudProcessing
3. Start OIP
4. Open .ptx file
5. See error

**Expected behavior**
OIP should not crash upon opening .ptxfiles

### LINKED ISSUE #510: [BUG] STL file format causes the OIP to crash
**Describe the bug**
Upon opening .stl file in OIP, OIP crashes.

**To Reproduce**

1. In CMAKE select OIP_WITH_POINT_CLOUD_PROCESSING and generate solution anew
2. Build OpenInfraPlatform.PointCloudProcessing
3. Start OIP
4. Open .stl file
5. See error

**Expected behavior**
OIP should not crash upon opening .stl files

**Screen shot**
image

### PR DESCRIPTION
**Pull request by SamuilsRulovs**
To ease search and implementation of Point Cloud formats, I have created a list of supported Point Cloud formats

Fixes #500 
Fixes #503 
Fixes #510

### CODE REVIEW

**Comment by SamuilsRulovs** [comment]
Work still in progress

**Comment by SamuilsRulovs** [comment]
After last changes .obj; .ptx; and .stl files are working

PTX example: 
OIP:
image
Original:
pump

STL example:
image

**Review by jschlenger — COMMENTED** [review]
Looks very good. Putting together a list with all sorts of file formats is a very good idea. I don't think you missed any important ones. 
Nice to see that you already managed to make quite some progress even with just small changes. Hopefully it stays that simple for some of the other file formats as well.

**Comment by jschlenger** [comment]
Are you going to tackle some of the other file formats in a separate pull request?

**Comment by SamuilsRulovs** [comment]
Yes, I guess it will be better to tackle other file formats as separate issues

**Pull request merged**
