### PR TITLE
Doxygen executables issue66

### PR DESCRIPTION
**Pull request by ghost**
Solved CMake not finding dot and doxygen executables (find_file instead of find_path for executables). Resolves issue #66.

### CODE REVIEW

**Comment by pjanck** [comment]
I thought that the Cmake files were not needed anymore. @hechth can you please take a look?

**Comment by pjanck** [comment]
Please see commit 87621f24baa946f0516dc74e738667e7f1ca94d8

**Comment by hechth** [comment]
Don't know how @ccoetzee implemented it so don't know which files are required. But generating the documentation on my machine worked fine!

**Comment by ghost** [comment]
I removed the 6 cmake files again, thought it was something I moved by accident, but I remember now you said they're not necessary anymore

**Comment by pjanck** [comment]
Resolves #66 .

**Pull request merged**
