### PR TITLE
Decreased density of mesh grid lines on B-spline surface

### LINKED ISSUE #542: Less dense mesh grid lines for b-spline surfaces
> skip curve points

Good idea. Since we're multiplying with 10, lets make it every 5th point (this way it always works in division).

_Originally posted by @pjanck in https://github.com/tumcms/Open-Infra-Platform/issues/538#issuecomment-1103885020_

### PR DESCRIPTION
**Pull request by christophKaiser**
New algorithm which skips evaluation points of B-spline surfaces to decrease their density.
Will close #542.

The adjustment in commit 5473e99 affects all B-splines - curves and surfaces. I though this change would be nice to achieve an even subdivision (issue of +/-1, if switch from points to spaces between points). The even subdivition leads to a homogeneous size of grid squares, thus a nice visualisation.

Pending:
- [x] Update Unit Tests which include B-splines (curves and surfaces).
  Would wait until there isn't a major change in code.

### CODE REVIEW

**Review by pjanck — COMMENTED** [review]
LFTM, code wise.

Can you post a screen shot of the new look, please?

I'll approve when the unit tests are updated.

**Review by jschlenger — COMMENTED** [review]
Nice implementation to skip some of the lines.
I like that it can be easily adjusted at any time.
Also waiting for the unit test adaption to approve the pull request.

**Review by pjanck — APPROVED** [review]
Great work, it looks fresher :)

**Comment by christophKaiser** [comment]
Missed comment about last commits.
The resent seven commits update the unit tests which contain B-spline curves and surfaces.
The update of curves is included, because the previous commit 5473e99 changed the number of evaluation points (curve points). The change in the visualization is just very minor, because only one point is added. However, the updates are done to apply the changes continuously.

**Review by jschlenger — COMMENTED** [review]
Looks very good! I like the changes.
Could you update the release notes , just making a very small entry about this change?

**Comment by christophKaiser** [comment]
> Could you update the release notes , just making a very small entry about this change?

Done in commit fdb4827.
I'm not sure about the category _Various improvements_. However, I haven't found a better one in the little amount of time.

**Review by jschlenger — APPROVED** [review]
Adding it to "Various Improvements" is completely fine.

**Pull request merged**
