### PR TITLE
IfcSeventhOrderPolynomialSpiral

### PR DESCRIPTION
**Pull request by Elvira2227**
In this pull request I implemented functions for reading the `IfcThirdOrderPolynomialSpiral`.
Now we can implement "VienneseBend curve" and this pull request can be addressed to issue #524.
In the CurveConverter.h I added:
1. `getPointOnCurve()` 
2. `getDirectionOfCurve()`
3. additional statement in `convertIfcCurveSegment()`

During visualisation, there is an error in the unit test data #478. 
1. Line 98 parameter ParentCurve is missing

### CODE REVIEW

**Review by pjanck — APPROVED** [review]
I assume that unit tests work correctly.

**Comment by jschlenger** [comment]
Is just the unit test not working properly?
Does the visualization in OIP work?

**Review by jschlenger — APPROVED** [review]
Looks fine

**Comment by jschlenger** [comment]
Can you create an issue to check for the correctness of IfcSeventhOrderPolynomialSpiral with an example file?
I know the code is very similar to other polynomial spirals, nevertheless to remember to check its functionality as soon as we have an example file.

**Review by pjanck — APPROVED** [review]
lftm

Is there an issue/PR with the unit tests?

**Pull request merged**
