### PR TITLE
Implementing "blend" function for a separate object

### LINKED ISSUE #437: [REQUEST] Implement “blending” function for a separate object in OIP Viewer
**Is your feature request related to a problem? Please describe.**

Right now, OIP can open several Ifc Files at the same time, thus it is necessary to implement several functionalities, which would help to navigate between those objects. Blending separate object is one of them. 

**Describe the solution you'd like**

Create function “Blending”, which will zoom in to the object selected.

### PR DESCRIPTION
**Pull request by SamuilsRulovs**
Fixes #437

### CODE REVIEW

**Comment by jschlenger** [comment]
It seems like Github is heaving some bugs since I'm not able to leave a review. So far everything seems to be fine. I guess you still need to fill the function on_actionBlendObject_triggered() with content. I'm also not quite sure what functionality you exactly mean with "blend".

**Review by jschlenger — COMMENTED** [review]
Now the reviewing seems to work again. Take a look at my comment before.

**Comment by jschlenger** [comment]
Maybe you need to make some small changes to Viewport.cpp.
Starting in line 805 the ifcGeometryEffects for all of the models coming from data.getModels() are initiated.
Adding some functionality that skips the models that are currently invisible (but not deleted) could make sense.
Maybe there are smarter solutions to solve this.

**Comment by SamuilsRulovs** [comment]
I am removing this pull request since there is no essential code (All included code is a copy of the code in PR #471)

**Pull request closed without merging**
